sudo: required
language: rust
cache: cargo
rust:
  - nightly
  - beta
  - stable
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - [[ "${TRAVIS_RUST_VERSION}" == "nightly" ]] && rustup component add clippy-preview
  - rustup component add rustfmt-preview
script:
  - [[ "${TRAVIS_RUST_VERSION}" == "nightly" ]] && cargo fmt -- --check
  - cargo build --verbose
  - cargo check
  - [[ "${TRAVIS_RUST_VERSION}" == "nightly" ]] && cargo clippy
  - cargo test --verbose
addons:
  apt:
    packages:
      - libdbus-1-dev
      - libgdk-pixbuf2.0-dev
      - libglib2.0-dev
      - libnotify-dev
notifications:
  email:
    on_success: never
