sudo: required
language: rust
cache: cargo
rust:
  - nightly
  - beta
  - stable
before_script:
  - |
    if [[ "${TRAVIS_RUST_VERSION}" == "nightly" ]]; then
      cargo install cargo-update || echo "cargo-update already installed"
      cargo install clippy || echo "clippy already installed"
      cargo install-update -a
    fi
  - rustup component add rustfmt-preview
script:
  - |
    if [[ "${TRAVIS_RUST_VERSION}" == "nightly" ]]; then
      cargo fmt -- --check
    fi
  - cargo build --verbose
  - |
    if [[ "${TRAVIS_RUST_VERSION}" == "nightly" ]]; then
      cargo clippy
    fi
  - cargo test --verbose
addons:
  apt:
    packages:
      - libdbus-1-dev
      - libgdk-pixbuf2.0-dev
      - libglib2.0-dev
      - libnotify-dev
notifications:
  email:
    on_success: never
