sudo: required
language: rust
cache: cargo
rust:
  - nightly
  - beta
  - stable
before_script:
  - rustup component add rustfmt-preview
script:
  - |
    if [[ "${TRAVIS_RUST_VERSION}" == "nightly" ]]; then
      cargo fmt -- --write-mode=diff
    fi
  - |
    if [[ "${TRAVIS_RUST_VERSION}" == "nightly" ]]; then
      cargo build --features dev
    else
      cargo build
    fi
  - cargo test
addons:
  apt:
    packages:
      - libdbus-1-dev
      - libgdk-pixbuf2.0-dev
      - libglib2.0-dev
      - libnotify-dev
notifications:
  email:
    on_success: never
