[package]
authors = ["Tobias Happ <tobias.happ@gmx.de>"]
description = "Displays system information for dwm status bar."
keywords = ["dwm", "dwm-status"]
license = "MIT"
name = "dwm-status"
readme = "README.md"
repository = "https://github.com/Gerschtli/dwm-status"
version = "1.6.2"
edition = "2018"
[badges.travis-ci]
branch = "master"
repository = "Gerschtli/dwm-status"

[dependencies]
chrono = "0.4.7"
clap = "2.33.0"
config = "0.9.3"
dbus = "0.6.4"
inotify = "0.7.0"
libnotify = "1.0.3"
log = "0.4.7"
serde = "1.0.94"
serde_derive = "1.0.94"
simplelog = "0.6.0"

[dependencies.ctrlc]
features = ["termination"]
version = "3.1.3"

[dependencies.mocktopus]
optional = true
version = "0.7.2"

[dependencies.x11]
features = ["xlib"]
version = "2.18.1"

[dev-dependencies]
hamcrest2 = "0.2.6"

[features]
mocking = ["mocktopus"]
