[package]
authors = ["Tobias Happ <tobias.happ@gmx.de>"]
name = "dwm-status"
version = "0.1.0"
description = "Displays system information for dwm status bar."

[dependencies]
chrono = "0.4.0"
clap = "2.30.0"
libnotify = "1.0.3"
