[package]
authors = ["Tobias Happ <tobias.happ@gmx.de>"]
description = "Displays system information for dwm status bar."
keywords = ["dwm", "dwm-status"]
license = "MIT"
name = "dwm-status"
readme = "README.md"
repository = "https://github.com/Gerschtli/dwm-status"
version = "0.5.1"
[badges.travis-ci]
branch = "master"
repository = "Gerschtli/dwm-status"

[dependencies]
chrono = "0.4.2"
dbus = "0.6.1"
inotify = "0.5.1"
libnotify = "1.0.3"

[dependencies.ctrlc]
features = ["termination"]
version = "3.1.1"

[dependencies.uuid]
features = ["v4"]
version = "0.6.5"

[dependencies.x11]
features = ["xlib"]
version = "2.18.0"
