[package]
authors = ["Tobias Happ <tobias.happ@gmx.de>"]
description = "Displays system information for dwm status bar."
name = "dwm-status"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/Gerschtli/dwm-status"
readme = "README.md"
keywords = ["dwm", "dwm-status"]

[badges.travis-ci]
repository = "Gerschtli/dwm-status"
branch = "master"

[dependencies]
chrono = "0.4.0"
dbus = "0.6.1"
inotify = "0.5.1"
libnotify = "1.0.3"

[dependencies.clippy]
optional = true
version = "0.0.189"

[dependencies.uuid]
features = ["v4"]
version = "0.6.1"

[features]
default = []
dev = ["clippy"]
