[package]
authors = ["Tobias Happ <tobias.happ@gmx.de>"]
description = "Displays system information for dwm status bar."
name = "dwm-status"
version = "0.1.0"

[dependencies]
chrono = "0.4.0"
dbus = "0.6.1"
inotify = "0.5.1"
libnotify = "1.0.3"

[dependencies.clippy]
optional = true
version = "0.0.188"

[dependencies.uuid]
features = ["v4"]
version = "0.6.1"

[features]
default = []
dev = ["clippy"]
