[package]
authors = ["Tobias Happ <tobias.happ@gmx.de>"]
description = "Displays system information for dwm status bar."
keywords = ["dwm", "dwm-status"]
license = "MIT"
name = "dwm-status"
readme = "README.md"
repository = "https://github.com/Gerschtli/dwm-status"
version = "1.5.0"
[badges.travis-ci]
branch = "master"
repository = "Gerschtli/dwm-status"

[dependencies]
chrono = "0.4.6"
clap = "2.32.0"
config = "0.9.1"
dbus = "0.6.3"
inotify = "0.6.1"
libnotify = "1.0.3"
log = "0.4.6"
serde = "1.0.80"
serde_derive = "1.0.80"
simplelog = "0.5.3"

[dependencies.ctrlc]
features = ["termination"]
version = "3.1.1"

[dependencies.x11]
features = ["xlib"]
version = "2.18.1"

[features]
rust-1-31 = []
